### ISSUE TITLE
“学术生涯”任务无法完成

### ISSUE THREAD

**Issue by OkamiWong** [OkamiWong/virtual-campus#2]
自教授：“选了理工学院，答完题都对了就没对话了。任务还卡在学术生涯，但是跟院长对话就没有相应的选项了。卡在这里了。“
![image](https://user-images.githubusercontent.com/24769875/90339358-d2e5b200-e022-11ea-9711-c0c9597594f3.png)

**Comment by ubcweicai** [comment]
之前打错了好多次，可能是这个原因。

**Comment by SydianAndrewChen** [comment]
已经修复完成了，因为按钮生成时忘调成可重复了
